### ISSUE TITLE
Get Travis CI green

### ISSUE THREAD

**Issue by bethesque** [webmachine/webmachine-ruby#217]
It's not providing useful feedback at the moment because it's hard to tell if it's an "expected failure" or a new bug. Also, it looks bad having the Travis CI tag being red all the time on the README. Actors in JRuby seems to be the issue at the moment - I had a quick look at https://github.com/seancribbs/webmachine-ruby/issues/126 and it seems it's not a quick or obvious fix. Can I put a skip in them for jruby so that we don't run them?

**Comment by Asmod4n** [comment]
It fails because of https://travis-ci.org/seancribbs/webmachine-ruby/jobs/45870930, rbx again.

Von einem mobilen Gerät gesendet

**Comment by bethesque** [comment]
We can close this when PR is merged. https://github.com/seancribbs/webmachine-ruby/pull/220

**Comment by bethesque** [comment]
I'm a bit confused https://travis-ci.org/seancribbs/webmachine-ruby/builds/47089373

rbx-2 is failing, but is not in the Travis list of allowed failures. Any idea why the badge is green?

**Comment by Asmod4n** [comment]
closed via #233
