### ISSUE TITLE
Migration to Webmachine organization

### ISSUE THREAD

**Issue by seancribbs** [Webmachine/webmachine-ruby#228]
In the past week we have birthed a [new organization](//github.com/Webmachine) on Github, just for Webmachine! 

I'd love to broach the topic of moving webmachine-ruby into that organization. The goals of this would be:

* Show that wm.rb is not just my project any more, increase the bus factor
* Encourage larger discussions around design across multiple language runtimes
* Promote the webmachine model in general

If everyone is up for this, I'll initiate the transition this week. Everyone who is an existing committer would retain rights.

**Comment by Asmod4n** [comment]
No objections :)

**Comment by bethesque** [comment]
Sounds like a good plan.

**Comment by seancribbs** [comment]
The move is complete! Please accept your invitations to the organization.
