### ISSUE TITLE
FSM diagram has moved

### ISSUE THREAD

**Issue by bethesque** [webmachine/webmachine-ruby#231]
The docs point to http://webmachine.basho.com/images/http-headers-status-v3.png, but it no longer exists. Got a replacement URL @seancribbs ?

**Comment by Asmod4n** [comment]
You mean this? https://github.com/webmachine/webmachine-ruby/blob/master/lib/webmachine/trace/static/http-headers-status-v3.png

**Comment by bernd** [comment]
Maybe use https://webmachine.github.io/images/http-headers-status-v3.png?

**Comment by seancribbs** [comment]
What @bernd @Asmod4n said. :smile:

**Comment by bethesque** [comment]
Updated, thanks.
