### ISSUE TITLE
No easy way to add tests for HTTP2/SSL adapter

### ISSUE THREAD

**Issue by rfestag** [webmachine/webmachine-ruby#243]
I am trying to add support for an HTTP2 adapter (based on @kenichi's h2 branch of Reel: https://github.com/celluloid/reel/pull/242). The catch is that it will require a different ruby client in order to make test requests, and ideally would use SSL to make the request (since that is what browsers will require).

I could simply copy lib/webmachine/spec/adpater_lint.rb and replace all calls to use an H2 client, but then we'd have to maintain the same test requests in two places. Does anyone have any thoughts on how to refactor adapter_lint.rb to make the requesting mechanism more generic?

**Comment by seancribbs** [comment]
I think we still haven't resolved this issue generally, but Reel is no longer in the latest version. Closing.
