### ISSUE TITLE
Ruby 2.4 support - use Integer instead of Fixnum

### ISSUE THREAD

**Issue by bethesque** [webmachine/webmachine-ruby#244]
Hoping this can be done in a backwards compatible way. I'll have a play with this if I can find the time, but it will be very low priority. I'm putting this up here in case anyone else wants to have a go.

**Comment by r-obert** [comment]
probably fixed by https://github.com/webmachine/webmachine-ruby/pull/246

**Comment by bethesque** [comment]
Yes. Will close when I do a release.

**Comment by pawelpacana** [comment]
This can be closed now (released).
