### ISSUE TITLE
Missing Celluloid dependency

### ISSUE THREAD

**Issue by JustAnotherArchivist** [webmachine/webmachine-ruby#259]
As far as I can tell, there's a dependency on Celluloid missing from Webmachine's Gemfile. The reel adapter requires Celluloid >= 0.17.0 since #233 due to `require 'celluloid/current'`. In my case, an older version was installed due to a dependency from an unrelated gem, which led to a LoadError on trying to use Webmachine.

(Sorry if I'm misunderstanding something here; I'm not very familiar with the Ruby world.)

**Comment by bethesque** [comment]
Yeah, this is affecting the build too. I've been meaning to look into it. I'll try and schedule it into my next OSS day if someone else doesn't manage to pick it up.

**Comment by bethesque** [comment]
https://github.com/webmachine/webmachine-ruby/pull/260
